# Cloudflare configuration for Executive AI Training
# This file is for local development with wrangler
# Pages deployment is configured in Cloudflare dashboard

name = "executive-ai-training"
compatibility_date = "2025-01-31"
compatibility_flags = ["nodejs_compat"]

# Note: For Pages deployment, configure build settings in Cloudflare dashboard:
# - Build command: npm run build
# - Build output directory: dist
# - Environment variables: Set in dashboard Settings